name: Debricked scan

on: [push]

jobs:
  vulnerabilities-scan-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          mvn --version
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}

  vulnerabilities-scan-staging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN_STAGING }}
          DEBRICKED_URI: 'https://staging.debricked.com'

  vulnerabilities-scan-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN_STAGING }}
          DEBRICKED_URI: 'https://review-7335-postg-rt1bzk.review.debricked.dev'
